name: myapp
description: "A real-time object detection Flutter project using ML Kit."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust SDK version if needed based on your setup

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_image_labeling: ^0.13.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/object.png
    - assets/ml/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
